export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as LogIn } from "./LogIn";
export { default as HomePage } from "./HomePage";
export { default as Register } from "./Register";
export { default as PostList } from "./PostList";
export { default as PostCard } from "./PostCard";
export {default as SinglePost} from "./SinglePost";
export {default as NewPost} from "./NewPost";
export {default as EditPost} from "./EditPost";
